// 默认轨道数目
export const DEFAULT_TRACK_SIZE = 30;
// 弹幕入画的最大时延
export const BarrageDelayedMaxTime = 10
// 弹幕的最大移动速度
export const BarrageMaxSpeed = 4

export const lyrics = [
  {
    value: 'I have this thing where I get older but just never wiser',
    time: 7,
    color: "#FFFFFF",
    speed: 2.7,
    fontSize: 24,
  },
  {
    value: '我怎么年纪渐长却没有更明智呢？！',
    time: 7,
    color: "#FFFFFF",
    speed: 2.8,
    fontSize: 24,
  },
  {
    value: 'Midnights become my afternoons',
    time: 10,
    color: "#FFFFFF",
    speed: 3.2,
    fontSize: 24,
  },
  {
    value: '每晚半夜还变成了我的午后时光',
    time: 11,
    color: "#FFFFFF",
    speed: 3.2,
    fontSize: 24,
  },
  {
    value: 'When my depression works the graveyard shift',
    time: 15,
    color: "#FFFFFF",
    speed: 2.6,
    fontSize: 24,
  },
  {
    value: '夜晚抑郁笼罩周围仿佛跻身幽森墓地',
    time: 15,
    color: "#FFFFFF",
    speed: 2.7,
    fontSize: 24,
  },
  {
    value: `All of the people I've ghosted stand there in the room`,
    time: 20,
    color: "#FFFFFF",
    speed: 2.8,
    fontSize: 24,
  },
  {
    value: '我曾经亏欠过的人全都浮现在眼前  ',
    time: 20,
    color: "#FFFFFF",
    speed: 3.2,
    fontSize: 24,
  },
  {
    value: 'I should not be left to my own devices',
    time: 25,
    color: "#FFFFFF",
    speed: 2.5,
    fontSize: 24,
  },
  {
    value: '我就不该自甘堕落',
    time: 25,
    color: "#FFFFFF",
    speed: 2.5,
    fontSize: 24,
  },
  {
    value: 'They come with prices and vices， I end up in crisis',
    time: 28,
    color: "#FFFFFF",
    speed: 3.2,
    fontSize: 24,
  },
  {
    value: '最后自食恶果，陷入名誉危机',
    time: 28,
    color: "#FFFFFF",
    speed: 3.4,
    fontSize: 24,
  },
  {
    value: '（Tale as old as time 都是陈腔滥调罢了 ）',
    time: 33,
    color: "#FFFFFF",
    speed: 2.7,
    fontSize: 24,
  },
  {
    value: 'I wake up screaming from dreaming',
    time: 36,
    color: "#FFFFFF",
    speed: 2.8,
    fontSize: 24,
  },
  {
    value: '我从噩梦中惊醒失声哭喊',
    time: 36,
    color: "#FFFFFF",
    speed: 2.7,
    fontSize: 24,
  },
  {
    value: `One day I'll watch as you're leaving`,
    time: 38,
    color: "#FFFFFF",
    speed: 3,
    fontSize: 24,
  },
  {
    value: '我梦到有一天我眼睁睁看着你们离开我',
    time: 38,
    color: "#FFFFFF",
    speed: 3,
    fontSize: 24,
  },
  {
    value: 'Cause you got tired of my scheming',
    time: 40,
    color: "#FFFFFF",
    speed: 2.8,
    fontSize: 24,
  },
  {
    value: '因为你们已经受够了我的小心机',
    time: 40,
    color: "#FFFFFF",
    speed: 2.8,
    fontSize: 24,
  },
  {
    value: 'For the last time 与我至此诀别了',
    time: 42,
    color: "#FFFFFF",
    speed: 3,
    fontSize: 24,
  },
  {
    value: `It's me hi I'm the problem it's me`,
    time: 45,
    color: "#CCCCFF",
    speed: 2.5,
    fontSize: 24,
  },
  {
    value: '其实是我，嗨！我才是问题所在！就是我啊',
    time: 45,
    color: "#CCCCFF",
    speed: 2.6,
    fontSize: 24,
  },
  {
    value: "At teatime everybody agrees",
    time: 49,
    color: "#FFFFFF",
    speed: 2.2,
    fontSize: 24,
  },
  {
    value: "茶余饭后，所有人都点头同意",
    time: 49,
    color: "#FFFFFF",
    speed: 2.2,
    fontSize: 24,
  },
  {
    value: `I'll stare directly at the sun but never in the mirror`,
    time: 55,
    color: "#FFFFFF",
    speed: 2.8,
    fontSize: 24,
  },
  {
    value: "我敢直视阳光却不敢正视镜子里的自己",
    time: 55,
    color: "#FFFFFF",
    speed: 3.2,
    fontSize: 24,
  },
  {
    value: "It must be exhausting always rooting for the anti-hero",
    time: 60,
    color: "#FFFFFF",
    speed: 2.5,
    fontSize: 24,
  },
  {
    value: "耗尽心机力挺我这种“反英雄偶像”肯定心力憔悴吧！",
    time: 62,
    color: "#FFFFFF",
    speed: 2.4,
    fontSize: 24,
  },
  {
    value: `Sometimes I feel like everybody is a sexy baby`,
    time: 72,
    color: "#FFFFFF",
    speed: 3,
    fontSize: 24,
  },
  {
    value: "有时我感觉身边所有人都魅力四射",
    time: 72,
    color: "#FFFFFF",
    speed: 3.2,
    fontSize: 24,
  },
  {
    value: `And I'm a monster on the hill`,
    time: 78,
    color: "#FFFFFF",
    speed: 3.3,
    fontSize: 24,
  },
  {
    value: `而我像只山野巨兽格格不入`,
    time: 78,
    color: "#FFFFFF",
    speed: 3.4,
    fontSize: 24,
  },
  {
    value: `Too big to hang out， slowly lurching toward your favorite city`,
    time: 80,
    color: "#FFFFFF",
    speed: 2.8,
    fontSize: 24,
  },
  {
    value: `身形太庞大没人和我玩，我只好匍匐着爬向你最爱的城市找你`,
    time: 81,
    color: "#FFFFFF",
    speed: 2.6,
    fontSize: 24,
  },
  {
    value: `Pierced through the heart but never killed`,
    time: 85,
    color: "#FFFFFF",
    speed: 3,
    fontSize: 24,
  },
  {
    value: `路上被万箭穿心，痛不欲生`,
    time: 85,
    color: "#FFFFFF",
    speed: 2.8,
    fontSize: 24,
  },
  {
    value: `Did you hear my covert narcissism I disguise as altruism    `,
    time: 88,
    color: "#CCCCCC",
    speed: 3,
    fontSize: 24,
  },
  {
    value: `你看穿了我拼命掩饰的自私了吗? 我拼命伪装成无私`,
    time: 89,
    color: "#CCCCCC",
    speed: 3.1,
    fontSize: 24,
  },
  {
    value: `Like some kind of congressman`,
    time: 92,
    color: "#CCCCCC",
    speed: 2.2,
    fontSize: 24,
  },
  {
    value: `虚伪得像某些国会议员一样`,
    time: 92,
    color: "#CCCCCC",
    speed: 2.4,
    fontSize: 24,
  },
  {
    value: `Tale as old as time `,
    time: 95,
    color: "#CCCCCC",
    speed: 3.2,
    fontSize: 24,
  },
  {
    value: `都是陈腔滥调罢了`,
    time: 95,
    color: "#CCCCCC",
    speed: 3.4,
    fontSize: 24,
  },
  {
    value: `I wake up screaming from dreaming `,
    time: 100,
    color: "#CCCCCC",
    speed: 3.2,
    fontSize: 24,
  },
  {
    value: `我从噩梦中惊醒失声哭喊`,
    time: 100,
    color: "#CCCCCC",
    speed: 3.4,
    fontSize: 24,
  },
  {
    value: `One day I'll watch as you're leaving`,
    time: 101,
    color: "#CCCCCC",
    speed: 2.2,
    fontSize: 24,
  },
  {
    value: `我梦到有一天我眼睁睁看着你离开我`,
    time: 102,
    color: "#CCCCCC",
    speed: 2.4,
    fontSize: 24,
  },
  {
    value: `And life will lose all its meaning`,
    time: 104,
    color: "#CCCCCC",
    speed: 3,
    fontSize: 24,
  },
  {
    value: `生命的意义将荡然无存`,
    time: 105,
    color: "#CCCCCC",
    speed: 3.1,
    fontSize: 24,
  },
  {
    value: `For the last time`,
    time: 106,
    color: "#CCCCCC",
    speed: 2.5,
    fontSize: 24,
  },
  {
    value: `I have this dream my daughter-in-law kills me for the money`,
    time: 138, //2'18''
    color: "#CCCCCC",
    speed: 3.1,
    fontSize: 24,
  },
  {
    value: `我做了一个梦，梦中我未来的儿媳会为了遗产谋杀我`,
    time: 139,
    color: "#CCCCCC",
    speed: 3.2,
    fontSize: 24,
  },
  {
    value: `She thinks I left them in the will`,
    time: 140,
    color: "#CCCCCC",
    speed: 2.6,
    fontSize: 24,
  },
  {
    value: `她以为我的遗嘱会将遗产传承给他们`,
    time: 141,
    color: "#CCCCCC",
    speed: 2.4,
    fontSize: 24,
  },
  {
    value: `The family gathers around and reads it and then someone screams out`,
    time: 144,
    color: "#CCCCCC",
    speed: 3,
    fontSize: 24,
  },
  {
    value: `在我的葬礼上家族成员高朋满座，遗嘱念到一半被一声惊叫打断`,
    time: 145,
    color: "#CCCCCC",
    speed: 3.1,
    fontSize: 24,
  },
  {
    value: `"She's laughing up at us from hell"`,
    time: 148,
    color: "#CCCCCC",
    speed: 3.1,
    fontSize: 24,
  },
  {
    value: `“这死老太婆在地府疯狂嘲笑我们呢！”`,
    time: 150,
    color: "#CCCCCC",
    speed: 3.1,
    fontSize: 24,
  },
]
export const repeated = [
  '女王行为，你已经三连冠了！',
  '你出息了你，妈妈不仅给你打单，还给你mix很多版本，你也很出息，给妈妈回馈冠单，这里为lover有首歌默哀',
  '这首歌很私人，Taylor向我们展示了她的不安她的自我怀疑甚至厌弃',
  '路人粉为Anti-Hero 全款买下新专',
  '你好！是我！热百三周冠的热单',
  '霉霉真的很棒',
  '感觉这首歌很适合ENFP',
  '一定是最近十年内最好听的首单之一，非常棒的一首歌',
  '我后面的歌都还没听到 这两天一直在循环这首 任何人不喜欢这首我都会伤心的',
  '专辑发行前泰勒斯还提到提到Anti-Hero是她写过最喜欢的歌之一，本来感觉下一个“受害者”出现了，结果竟然是首单，可能这就是命吧，某车，某夏，流放，八月…终究是错付了',
  '感觉整个世界只有泰勒斯能和我共情',
  '听了好多remix,原版更好听了',
  '这首刚听觉得一般 越听越好听！！真的！！我已经上头了啊啊啊啊！！配上mv一起更绝',
  'midnights真的适合midnight听……',
  '这是一条三十五元的评论，这首全专最爱',

]
export const data = [
  {
    value: "Taylor Swift 的 Anti Hero，循环 N 遍了",
    time: 5,
    color: "red",
    speed: 3,
    fontSize: 22,
  },
  {
    value: '泰勒还是美的',
    time: 8, // 0'08''
    color: '#6666FF',
    speed: 3,
    fontSize: 24,
  },
  {
    value: `配文"the tea time is coming"意思是吃瓜时间到，所以这句是霉那段时间的心理，认为人人都讨厌她，人人都背叛她，甚至自己也开始自我厌恶`,
    time: 50,
    color: "#FFFFFF",
    speed: 2.4,
    fontSize: 24,
  },
  {
    value: 'mv出事了家人们因为那个称重的片段',
    time: 130, // 2'10''
    color: '#6666FF',
    speed: 2.4,
    fontSize: 24,
  },
  {
    value:
      "遗嘱内容大致如下： 1.beach house会变成一个cat sanctuary（猫咪庇护所） 2.把大部分遗产都留给了她的三只猫 Meredith Grey Swift Olivia Berson Swift Benjamin Button Swift 3.每个孩子 13 cent",
    time: 150, // 2'30"
    color: "white",
    speed: 1.5,
    fontSize: 22,
  },
  {
    value:
      "霉霉这是把遗产都给猫了？给自己孩子留了13美分哈哈哈",
    time: 180, // 3'00"
    color: "white",
    speed: 3,
    fontSize: 22,
  },
  {
    value: `我霉太有才啦🤩🤩🤩“It's me，hi，I'm the problem”女王回归❤️被人排挤的巨人和葬礼上的财产争执，脑洞可太大啦😆完美诠释我霉被很多人讨厌但很爱自己也很爱粉丝！！！`,
    time: 258, // 4'18''
    color: '#6666FF',
    speed: 3,
    fontSize: 24,
  },
  {
    value:`OMG!"everybody agrees" 的s音托这么长很像蛇吐信子的声音，再结合歌词 I'm the problem，和金评霉时期被叫蛇🐍，然后这么处理这里的唱法。`,
    time: 272, // 4'32"
    color: "#FFFFFF",
    speed: 2.8,
    fontSize: 24,
  },
  {
    value:
      "每个我都是我讨厌的自己，肥胖巨大，不合群，孤僻，不讨人喜欢，我厌恶自己，但是最终每一个我讨厌的自己围坐在一起喝着酒，接纳每一个自己",
    time: 280, // 4'40"
    color: "#FFCC00",
    speed: 1.5,
    fontSize: 20,
  },
  {
    value:
      "MV总是意外的惊喜 ，跟着起起伏伏找到自己的领悟 ，我们内心住着多少个渺小又想冲破牢笼的自己？",
    time: 280, // 4'42"
    color: "#FF9999",
    speed: 1.2,
    fontSize: 22,
  },
  {
    value:
      "她用自嘲的方式来释怀",
    time: 280, // 4'45"
    color: "#009966",
    speed: 2,
    fontSize: 28,
  },
  {
    value: "接受每一个自己",
    time: 295,
    color: "red",
    speed: 3,
    fontSize: 28,
  },
  {
    value: "一度想成为hero，此时只是一个anti-hero。当三个Taylor在喝酒，我想自己也要爱自己啊",
    time: 296,
    color: "red",
    speed: 2.6,
    fontSize: 27,
  },
  {
    value: "要爱自己哦～",
    time: 300,
    color: "red",
    speed: 2.8,
    fontSize: 32,
  },
];
